name: snajdr.de
favicon: null
layout_spectrum: 0.3171483788173646
typography_spectrum: 0.18996014050208032
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.16657580551691353
  lightness: 0.6941482538823038
  saturation: 0.022315377835184336
  rhythmicContrast: 0.8340207373257726
purpose: []
