typography_spectrum: 0.576549621010107
color:
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  brandStrength: 0.9881981722966279
  lightness: 0.1542805800325062
  saturation: 0.9005473162826741
  rhythmicContrast: 0.7025444691193907
github: true
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.732882118705697
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Martin Snajdr
  email: martin@snajdr.de
  url: 'http://snajdr.de'
name: Martin Snajdr
url: 'https://snajdr.de'
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Blog
    url: 'https://blog.snajdr.de'
    type: external
  - name: Coach & Speaker
    id: 2bd33a62-4041-4d78-986e-87b173d724ae
    type: content
favicon: null
title: Martin Snajdr
content: []
description: Creative Technologist
purpose:
  - type: contact
    url: 'mailto:martin@snajdr.de'
    label: Contact me
